### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by alexbelgium** [hendrix04/mealie-combined#1]
Hi, this project is very interesting! Is it still updated? I see that the last image build on dockerhub was 5 months ago, but the last successfull api & frontend builds were 11 & 12 hours ago

Also, were you thinking of potentially supporting aarch64 also? As many users are with rpi4 :-)

Thanks for the feedback

**Comment by hendrix04** [comment]
It is something that I would still like to accomplish, but other projects started taking up more time. At the time I had gotten this to the point of starting up, but I could never get the UI to load.

I took aarch64 support out simply because it was taking me way too long to create and publish the container during my testing. I intended on adding it back in once I had something running.

I had picked it up a little bit ago, but the move of the caddie server messed with what I had done so that needs to be figured out / moved around.

**Comment by alexbelgium** [comment]
Ah, I understand you! And this kind of things take tons of time to put in place, with probably breaking changes due to the nightly status.

Wouldn't it be faster and easier to maintain by truly merging the current API and frontend containers by pulling the official images in your Dockerfile, copying the relevant folders in your base image, and managing the run of both services through the init or entrypoint scripts? I haven't looked closely but my main github activity is building addons for homeassistant which sometimes include this type of modification of preexisting images...

Anyway, good luck on your project! And thanks for the quick response!

**Comment by hendrix04** [comment]
Unfortunately, you can't really just smash 2 images together. I could in theory take the backend image and then build the front end stuff into it, but that would require installing node and everything that is in the node:16 base image.

Instead I chose to just try and rebuild it by pulling the original source. My idea was to make PRs to the original source to make this project as light weight as possible (and that is still certainly possible), but time got away from me. The long term plan was to lock the combined releases to official Mealie releases so that I didn't have to worry about it on a nightly basis. When I started this though, there weren't good tagged releases for mealie-next so I decided to just follow the nightly instead.

Once Mealie-Next goes 1.0 I intend on getting this fully going. Playing around with it a bit today, I am definitely a lot closer than I was 5 months ago.

**Comment by hendrix04** [comment]
@alexbelgium, One last update.

I got this working on my unraid server today (thanks for the push!). I haven't tested this with docker compose, but I just kicked off a build and included ARM as one of the targets. Give it a shot and let me know how it goes.

**Comment by alexbelgium** [comment]
Hi, thanks! I'll sure test it!

**Comment by alexbelgium** [comment]
Thanks very much for taking the time to work on that. I believe it will be useful to many people! 

- aarch64 : doesn't work - I have a `exec /bin/sh: exec format error` which should indicate a mismatch of architecture.
- amd64 :
  - [x] build works (I'm doing a custom build by adding things to you image)
  - [x] app boots
  - [x] login work
  - [x] recipe addition works
  => Looks like you have managed to make it work perfectly, congrats!

**Comment by hendrix04** [comment]
I greatly appreciate you testing this for me.

I opened a new issue for the aarch64 issue. Unfortunately, I don't have a spare Pi to diagnose the issue on. I will see if there is an obvious fix, but I may need to depend on you for more testing if you don't mind.

**Comment by alexbelgium** [comment]
Of course! I'll look on my side too. Thanks!
